# Generated by Django 5.1 on 2024-09-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telegram username'),
        ),
    ]
