# Generated by Django 5.1 on 2024-09-21 08:40

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[common.utils.phone_number_validator], verbose_name='phone number'),
        ),
    ]
