# Generated by Django 5.1 on 2024-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('product', '0003_product_price_product_quantity_discount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discount',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='action',
        ),
        migrations.AddField(
            model_name='product',
            name='desc_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_uz',
            field=models.TextField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount price'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
