# Generated by Django 5.1 on 2024-08-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusgallery',
            name='about_us',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='company.aboutus'),
        ),
    ]
