# Generated by Django 5.1 on 2024-08-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('company', '0002_alter_aboutusgallery_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusgallery',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media'),
        ),
    ]
