# Generated by Django 5.1 on 2024-09-21 08:40

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_aboutusgallery_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number2',
            field=models.CharField(max_length=20, validators=[common.utils.phone_number_validator], verbose_name='phone number2'),
        ),
        migrations.AlterField(
            model_name='contactwithus',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[common.utils.phone_number_validator], verbose_name='phone number'),
        ),
    ]
