# Generated by Django 4.1 on 2024-08-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='order number'),
        ),
    ]
