# Generated by Django 4.1 on 2024-08-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal_price',
            field=models.FloatField(blank=True, null=True, verbose_name='subtotal price'),
        ),
    ]
